---

- when: cloud_tags is defined
  block:
    - set_fact:
        cloud_tags_final: "{{ cloud_tags | from_json }}"
      when: cloud_tags is string

    - set_fact:
        cloud_tags_final: "{{ cloud_tags | d({}) }}"
      when: cloud_tags is not string

    - debug:
       var: cloud_tags_final

    - debug:
       var: default_metadata

    - set_fact:
        default_metadata: "{{ default_metadata | combine(cloud_tags_final) }}"

    - debug:
        var: default_metadata

- import_tasks: locate_template.yml

- import_tasks: generate_osp_template.yml